name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black ruff
      - name: Run lint
        run: |
          python -m black --check src
          python -m ruff check src
