name: Publish Rust crate
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  publish-crate:
    name: Publish crate to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Install Rust toolchain
      #   run: |
      #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      #     source $HOME/.cargo/env

      - name: Publish crate
        run: |
          cargo publish --manifest-path rust/Cargo.toml --dry-run
